[platformio]
default_envs = matrixportal_s3_stable

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  tzapu/WiFiManager @ ^2.0.17
  links2004/WebSockets @ ^2.6.1
  adafruit/Adafruit GFX Library @ ^1.12.4
build_flags =
  -DMICA_MATRIX_WIDTH=64
  -DMICA_MATRIX_HEIGHT=32
  -DMICA_STREAM_BINS=64
  -DMICA_PANEL_TYPE_HUB75_64X32=1

[env:matrixportal_s3_stable]
board = adafruit_matrixportal_esp32s3
build_flags =
  ${env.build_flags}
  -DMICA_PROFILE_STABLE=1
  -DMICA_BOARD_VARIANT_MATRIXPORTAL_S3=1
lib_deps =
  ${env.lib_deps}
  adafruit/Adafruit Protomatter @ ^1.7.0

[env:matrixportal_s3_dma_exp]
board = adafruit_matrixportal_esp32s3
build_flags =
  ${env.build_flags}
  -DMICA_PROFILE_DMA_EXP=1
  -DMICA_BOARD_VARIANT_MATRIXPORTAL_S3=1
lib_deps =
  ${env.lib_deps}
  https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git

[env:esp32s3_devkitc1_stable]
board = esp32-s3-devkitc-1
build_flags =
  ${env.build_flags}
  -DMICA_PROFILE_STABLE=1
  -DMICA_BOARD_VARIANT_ESP32S3_DEVKITC1=1
lib_deps =
  ${env.lib_deps}
  adafruit/Adafruit Protomatter @ ^1.7.0

[env:esp32s3_devkitc1_dma_exp]
board = esp32-s3-devkitc-1
build_flags =
  ${env.build_flags}
  -DMICA_PROFILE_DMA_EXP=1
  -DMICA_BOARD_VARIANT_ESP32S3_DEVKITC1=1
lib_deps =
  ${env.lib_deps}
  https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git

[env:matrixportal_s3_stable_release]
board = adafruit_matrixportal_esp32s3
build_flags =
  ${env.build_flags}
  -DMICA_PROFILE_STABLE=1
  -DMICA_BOARD_VARIANT_MATRIXPORTAL_S3=1
  -DMICA_SECURITY_PROFILE_RELEASE=1
lib_deps =
  ${env.lib_deps}
  adafruit/Adafruit Protomatter @ ^1.7.0

[env:matrixportal_s3_dma_exp_release]
board = adafruit_matrixportal_esp32s3
build_flags =
  ${env.build_flags}
  -DMICA_PROFILE_DMA_EXP=1
  -DMICA_BOARD_VARIANT_MATRIXPORTAL_S3=1
  -DMICA_SECURITY_PROFILE_RELEASE=1
lib_deps =
  ${env.lib_deps}
  https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git
