; DOCS: docs/wiki/modules/firmware-esp32s3-devkitc1.md#perfil-oficial
; DOCS: docs/wiki/reference/code-index.md
[platformio]
default_envs = esp32s3_devkitc1_dma_exp
boards_dir = boards

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  tzapu/WiFiManager @ ^2.0.17
  links2004/WebSockets @ ^2.6.1
  knolleary/PubSubClient @ ^2.8
  adafruit/Adafruit GFX Library @ ^1.12.4
build_flags =
  -DMICA_MATRIX_WIDTH=128
  -DMICA_MATRIX_HEIGHT=64
  -DMICA_STREAM_BINS=128
  -DMICA_PANEL_TYPE_HUB75_P2_5_128X64_SMD2121_SCAN32=1
  -DMICA_PROFILE_DMA_EXP=1
  -DMICA_TEST_LED_GPIO=-1
  -DWEBSOCKETS_MAX_DATA_SIZE=32768

[env:esp32s3_devkitc1_dma_exp]
board = mica_esp32_s3_devkitc1_n16r8
board_build.partitions = partitions/mica_app3M_fat9M_16MB.csv
build_flags =
  ${env.build_flags}
lib_deps =
  ${env.lib_deps}
  https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git
