<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MicaAudio.Core\MicaAudio.Core.csproj" />
    <ProjectReference Include="..\Device.Protocol\Device.Protocol.csproj" />
    <ProjectReference Include="..\Device.Server.Abstractions\Device.Server.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
