using Device.Protocol.Models;

namespace Device.Server.Hosting;

// DOCS: docs/wiki/modules/device-server-protocol.md#fluxo-de-execucao
internal static class DeviceRecordMutations
{
    public static DeviceRecord CreatePairedRecord(
        string deviceId,
        string token,
        string name,
        string profile,
        string? firmwareVersion,
        string? ip,
        string? boardModel,
        string? panelType,
        DateTimeOffset now)
    {
        return new DeviceRecord
        {
            DeviceId = deviceId,
            Token = token,
            Name = name,
            Profile = profile,
            CreatedAtUtc = now,
            LastSeenUtc = now,
            LastKnownIp = ip,
            FirmwareVersion = firmwareVersion,
            BoardModel = boardModel,
            PanelType = panelType,
            IsRegistered = true,
        };
    }

    public static DeviceRecord MarkSeen(
        DeviceRecord source,
        DateTimeOffset now,
        string? ip,
        int? rssi,
        string? firmwareVersion,
        string? activeAppId = null,
        string? activeAppName = null,
        string? boardModel = null,
        string? panelType = null)
    {
        ArgumentNullException.ThrowIfNull(source);

        return new DeviceRecord
        {
            DeviceId = source.DeviceId,
            Name = source.Name,
            Profile = source.Profile,
            Token = source.Token,
            IsRegistered = source.IsRegistered,
            CreatedAtUtc = source.CreatedAtUtc,
            LastSeenUtc = now,
            FirstSeenUtc = source.FirstSeenUtc,
            LastTelemetryUtc = source.LastTelemetryUtc,
            LastAuthUtc = source.LastAuthUtc,
            ConfigState = source.ConfigState,
            FirmwareVersion = string.IsNullOrWhiteSpace(firmwareVersion) ? source.FirmwareVersion : firmwareVersion,
            LastKnownIp = string.IsNullOrWhiteSpace(ip) ? source.LastKnownIp : ip,
            LastKnownRssi = rssi ?? source.LastKnownRssi,
            UptimeSeconds = source.UptimeSeconds,
            LoopHealthyPercent = source.LoopHealthyPercent,
            LoopLoadPercent = source.LoopLoadPercent,
            ChipTemperatureCelsius = source.ChipTemperatureCelsius,
            FreeHeapBytes = source.FreeHeapBytes,
            LargestHeapBlockBytes = source.LargestHeapBlockBytes,
            PsramAvailable = source.PsramAvailable,
            FreePsramBytes = source.FreePsramBytes,
            LargestPsramBlockBytes = source.LargestPsramBlockBytes,
            WifiConnected = source.WifiConnected,
            WifiState = source.WifiState,
            ProvisioningPortalActive = source.ProvisioningPortalActive,
            AuxLedAvailable = source.AuxLedAvailable,
            TestLedAvailable = source.TestLedAvailable,
            LastWifiEvent = source.LastWifiEvent,
            StreamLastSequence = source.StreamLastSequence,
            StreamFramesReceived = source.StreamFramesReceived,
            StreamFramesApplied = source.StreamFramesApplied,
            Hub75PresentFrames = source.Hub75PresentFrames,
            StreamSequenceGapCount = source.StreamSequenceGapCount,
            StreamInvalidFrameCount = source.StreamInvalidFrameCount,
            ResetReason = source.ResetReason,
            ControlQueueDepth = source.ControlQueueDepth,
            ControlWorkerState = source.ControlWorkerState,
            PanelsWorkerState = source.PanelsWorkerState,
            LastSlowCommand = source.LastSlowCommand,
            LastSlowCommandDurationMs = source.LastSlowCommandDurationMs,
            TelemetrySequence = source.TelemetrySequence,
            BrightnessCap = source.BrightnessCap,
            BrightnessRequested = source.BrightnessRequested,
            BrightnessApplied = source.BrightnessApplied,
            TestLedEnabled = source.TestLedEnabled,
            TestLedDuty = source.TestLedDuty,
            ActiveAppId = string.IsNullOrWhiteSpace(activeAppId) ? source.ActiveAppId : activeAppId,
            ActiveAppName = string.IsNullOrWhiteSpace(activeAppName) ? source.ActiveAppName : activeAppName,
            BoardModel = string.IsNullOrWhiteSpace(boardModel) ? source.BoardModel : boardModel,
            PanelType = string.IsNullOrWhiteSpace(panelType) ? source.PanelType : panelType,
            AnimatedWebpBatchSupported = source.AnimatedWebpBatchSupported,
            ChipModel = source.ChipModel,
            ChipRevision = source.ChipRevision,
            ChipCores = source.ChipCores,
            CpuFreqMHz = source.CpuFreqMHz,
            SdkVersion = source.SdkVersion,
            HeapTotalBytes = source.HeapTotalBytes,
            PsramTotalBytes = source.PsramTotalBytes,
            FlashTotalBytes = source.FlashTotalBytes,
            SketchSizeBytes = source.SketchSizeBytes,
            FreeSketchBytes = source.FreeSketchBytes,
        };
    }

    public static DeviceRecord MarkAuthenticated(DeviceRecord source, DateTimeOffset now)
    {
        ArgumentNullException.ThrowIfNull(source);

        return new DeviceRecord
        {
            DeviceId = source.DeviceId,
            Name = source.Name,
            Profile = source.Profile,
            Token = source.Token,
            IsRegistered = true,
            CreatedAtUtc = source.CreatedAtUtc,
            LastSeenUtc = source.LastSeenUtc,
            FirstSeenUtc = source.FirstSeenUtc ?? now,
            LastTelemetryUtc = source.LastTelemetryUtc,
            LastAuthUtc = now,
            ConfigState = DeviceConfigState.KnownGood,
            FirmwareVersion = source.FirmwareVersion,
            LastKnownIp = source.LastKnownIp,
            LastKnownRssi = source.LastKnownRssi,
            UptimeSeconds = source.UptimeSeconds,
            LoopHealthyPercent = source.LoopHealthyPercent,
            LoopLoadPercent = source.LoopLoadPercent,
            ChipTemperatureCelsius = source.ChipTemperatureCelsius,
            FreeHeapBytes = source.FreeHeapBytes,
            LargestHeapBlockBytes = source.LargestHeapBlockBytes,
            PsramAvailable = source.PsramAvailable,
            FreePsramBytes = source.FreePsramBytes,
            LargestPsramBlockBytes = source.LargestPsramBlockBytes,
            WifiConnected = source.WifiConnected,
            WifiState = source.WifiState,
            ProvisioningPortalActive = source.ProvisioningPortalActive,
            AuxLedAvailable = source.AuxLedAvailable,
            TestLedAvailable = source.TestLedAvailable,
            LastWifiEvent = source.LastWifiEvent,
            StreamLastSequence = source.StreamLastSequence,
            StreamFramesReceived = source.StreamFramesReceived,
            StreamFramesApplied = source.StreamFramesApplied,
            Hub75PresentFrames = source.Hub75PresentFrames,
            StreamSequenceGapCount = source.StreamSequenceGapCount,
            StreamInvalidFrameCount = source.StreamInvalidFrameCount,
            ResetReason = source.ResetReason,
            ControlQueueDepth = source.ControlQueueDepth,
            ControlWorkerState = source.ControlWorkerState,
            PanelsWorkerState = source.PanelsWorkerState,
            LastSlowCommand = source.LastSlowCommand,
            LastSlowCommandDurationMs = source.LastSlowCommandDurationMs,
            TelemetrySequence = source.TelemetrySequence,
            BrightnessCap = source.BrightnessCap,
            BrightnessRequested = source.BrightnessRequested,
            BrightnessApplied = source.BrightnessApplied,
            TestLedEnabled = source.TestLedEnabled,
            TestLedDuty = source.TestLedDuty,
            ActiveAppId = source.ActiveAppId,
            ActiveAppName = source.ActiveAppName,
            BoardModel = source.BoardModel,
            PanelType = source.PanelType,
            AnimatedWebpBatchSupported = source.AnimatedWebpBatchSupported,
            ChipModel = source.ChipModel,
            ChipRevision = source.ChipRevision,
            ChipCores = source.ChipCores,
            CpuFreqMHz = source.CpuFreqMHz,
            SdkVersion = source.SdkVersion,
            HeapTotalBytes = source.HeapTotalBytes,
            PsramTotalBytes = source.PsramTotalBytes,
            FlashTotalBytes = source.FlashTotalBytes,
            SketchSizeBytes = source.SketchSizeBytes,
            FreeSketchBytes = source.FreeSketchBytes,
        };
    }

    public static DeviceRecord MarkTelemetry(
        DeviceRecord source,
        DateTimeOffset now,
        string? ip,
        int? rssi,
        string? firmwareVersion,
        string? activeAppId = null,
        string? activeAppName = null,
        string? boardModel = null,
        string? panelType = null,
        int? uptimeSeconds = null,
        int? loopHealthyPercent = null,
        int? loopLoadPercent = null,
        double? chipTemperatureCelsius = null,
        long? freeHeapBytes = null,
        long? largestHeapBlockBytes = null,
        bool? psramAvailable = null,
        long? freePsramBytes = null,
        long? largestPsramBlockBytes = null,
        bool? wifiConnected = null,
        string? wifiState = null,
        bool? provisioningPortalActive = null,
        bool? auxLedAvailable = null,
        bool? testLedAvailable = null,
        string? lastWifiEvent = null,
        uint? streamLastSequence = null,
        uint? streamFramesReceived = null,
        uint? streamFramesApplied = null,
        uint? hub75PresentFrames = null,
        uint? streamSequenceGapCount = null,
        uint? streamInvalidFrameCount = null,
        string? resetReason = null,
        uint? controlQueueDepth = null,
        string? controlWorkerState = null,
        string? panelsWorkerState = null,
        string? lastSlowCommand = null,
        long? lastSlowCommandDurationMs = null,
        uint? telemetrySequence = null,
        int? brightnessCap = null,
        int? brightnessRequested = null,
        int? brightnessApplied = null,
        bool? testLedEnabled = null,
        int? testLedDuty = null,
        bool? animatedWebpBatchSupported = null)
    {
        ArgumentNullException.ThrowIfNull(source);

        return new DeviceRecord
        {
            DeviceId = source.DeviceId,
            Name = source.Name,
            Profile = source.Profile,
            Token = source.Token,
            IsRegistered = true,
            CreatedAtUtc = source.CreatedAtUtc,
            LastSeenUtc = now,
            FirstSeenUtc = source.FirstSeenUtc ?? now,
            LastTelemetryUtc = now,
            LastAuthUtc = source.LastAuthUtc,
            ConfigState = source.ConfigState,
            FirmwareVersion = string.IsNullOrWhiteSpace(firmwareVersion) ? source.FirmwareVersion : firmwareVersion,
            LastKnownIp = string.IsNullOrWhiteSpace(ip) ? source.LastKnownIp : ip,
            LastKnownRssi = rssi ?? source.LastKnownRssi,
            UptimeSeconds = uptimeSeconds,
            LoopHealthyPercent = loopHealthyPercent,
            LoopLoadPercent = loopLoadPercent,
            ChipTemperatureCelsius = chipTemperatureCelsius,
            FreeHeapBytes = freeHeapBytes,
            LargestHeapBlockBytes = largestHeapBlockBytes,
            PsramAvailable = psramAvailable,
            FreePsramBytes = freePsramBytes,
            LargestPsramBlockBytes = largestPsramBlockBytes,
            WifiConnected = wifiConnected,
            WifiState = wifiState,
            ProvisioningPortalActive = provisioningPortalActive,
            AuxLedAvailable = auxLedAvailable,
            TestLedAvailable = testLedAvailable,
            LastWifiEvent = lastWifiEvent,
            StreamLastSequence = streamLastSequence,
            StreamFramesReceived = streamFramesReceived,
            StreamFramesApplied = streamFramesApplied,
            Hub75PresentFrames = hub75PresentFrames,
            StreamSequenceGapCount = streamSequenceGapCount,
            StreamInvalidFrameCount = streamInvalidFrameCount,
            ResetReason = resetReason,
            ControlQueueDepth = controlQueueDepth,
            ControlWorkerState = controlWorkerState,
            PanelsWorkerState = panelsWorkerState,
            LastSlowCommand = lastSlowCommand,
            LastSlowCommandDurationMs = lastSlowCommandDurationMs,
            TelemetrySequence = telemetrySequence,
            BrightnessCap = brightnessCap,
            BrightnessRequested = brightnessRequested,
            BrightnessApplied = brightnessApplied,
            TestLedEnabled = testLedEnabled,
            TestLedDuty = testLedDuty,
            ActiveAppId = string.IsNullOrWhiteSpace(activeAppId) ? source.ActiveAppId : activeAppId,
            ActiveAppName = string.IsNullOrWhiteSpace(activeAppName) ? source.ActiveAppName : activeAppName,
            BoardModel = string.IsNullOrWhiteSpace(boardModel) ? source.BoardModel : boardModel,
            PanelType = string.IsNullOrWhiteSpace(panelType) ? source.PanelType : panelType,
            AnimatedWebpBatchSupported = animatedWebpBatchSupported ?? source.AnimatedWebpBatchSupported,
            ChipModel = source.ChipModel,
            ChipRevision = source.ChipRevision,
            ChipCores = source.ChipCores,
            CpuFreqMHz = source.CpuFreqMHz,
            SdkVersion = source.SdkVersion,
            HeapTotalBytes = source.HeapTotalBytes,
            PsramTotalBytes = source.PsramTotalBytes,
            FlashTotalBytes = source.FlashTotalBytes,
            SketchSizeBytes = source.SketchSizeBytes,
            FreeSketchBytes = source.FreeSketchBytes,
        };
    }

    public static DeviceRecord MarkStats(
        DeviceRecord source,
        DateTimeOffset now,
        string? ip,
        string? chipModel = null,
        int? chipRevision = null,
        int? chipCores = null,
        int? cpuFreqMHz = null,
        string? sdkVersion = null,
        long? heapTotalBytes = null,
        long? psramTotalBytes = null,
        long? flashTotalBytes = null,
        long? sketchSizeBytes = null,
        long? freeSketchBytes = null)
    {
        ArgumentNullException.ThrowIfNull(source);

        return new DeviceRecord
        {
            DeviceId = source.DeviceId,
            Name = source.Name,
            Profile = source.Profile,
            Token = source.Token,
            IsRegistered = source.IsRegistered,
            CreatedAtUtc = source.CreatedAtUtc,
            LastSeenUtc = now,
            FirstSeenUtc = source.FirstSeenUtc,
            LastTelemetryUtc = source.LastTelemetryUtc,
            LastAuthUtc = source.LastAuthUtc,
            ConfigState = source.ConfigState,
            FirmwareVersion = source.FirmwareVersion,
            LastKnownIp = string.IsNullOrWhiteSpace(ip) ? source.LastKnownIp : ip,
            LastKnownRssi = source.LastKnownRssi,
            UptimeSeconds = source.UptimeSeconds,
            LoopHealthyPercent = source.LoopHealthyPercent,
            LoopLoadPercent = source.LoopLoadPercent,
            ChipTemperatureCelsius = source.ChipTemperatureCelsius,
            FreeHeapBytes = source.FreeHeapBytes,
            LargestHeapBlockBytes = source.LargestHeapBlockBytes,
            PsramAvailable = source.PsramAvailable,
            FreePsramBytes = source.FreePsramBytes,
            LargestPsramBlockBytes = source.LargestPsramBlockBytes,
            WifiConnected = source.WifiConnected,
            WifiState = source.WifiState,
            ProvisioningPortalActive = source.ProvisioningPortalActive,
            AuxLedAvailable = source.AuxLedAvailable,
            TestLedAvailable = source.TestLedAvailable,
            LastWifiEvent = source.LastWifiEvent,
            StreamLastSequence = source.StreamLastSequence,
            StreamFramesReceived = source.StreamFramesReceived,
            StreamFramesApplied = source.StreamFramesApplied,
            Hub75PresentFrames = source.Hub75PresentFrames,
            StreamSequenceGapCount = source.StreamSequenceGapCount,
            StreamInvalidFrameCount = source.StreamInvalidFrameCount,
            ResetReason = source.ResetReason,
            ControlQueueDepth = source.ControlQueueDepth,
            ControlWorkerState = source.ControlWorkerState,
            PanelsWorkerState = source.PanelsWorkerState,
            LastSlowCommand = source.LastSlowCommand,
            LastSlowCommandDurationMs = source.LastSlowCommandDurationMs,
            TelemetrySequence = source.TelemetrySequence,
            BrightnessCap = source.BrightnessCap,
            BrightnessRequested = source.BrightnessRequested,
            BrightnessApplied = source.BrightnessApplied,
            TestLedEnabled = source.TestLedEnabled,
            TestLedDuty = source.TestLedDuty,
            ActiveAppId = source.ActiveAppId,
            ActiveAppName = source.ActiveAppName,
            BoardModel = source.BoardModel,
            PanelType = source.PanelType,
            AnimatedWebpBatchSupported = source.AnimatedWebpBatchSupported,
            ChipModel = string.IsNullOrWhiteSpace(chipModel) ? source.ChipModel : chipModel,
            ChipRevision = chipRevision ?? source.ChipRevision,
            ChipCores = chipCores ?? source.ChipCores,
            CpuFreqMHz = cpuFreqMHz ?? source.CpuFreqMHz,
            SdkVersion = string.IsNullOrWhiteSpace(sdkVersion) ? source.SdkVersion : sdkVersion,
            HeapTotalBytes = heapTotalBytes ?? source.HeapTotalBytes,
            PsramTotalBytes = psramTotalBytes ?? source.PsramTotalBytes,
            FlashTotalBytes = flashTotalBytes ?? source.FlashTotalBytes,
            SketchSizeBytes = sketchSizeBytes ?? source.SketchSizeBytes,
            FreeSketchBytes = freeSketchBytes ?? source.FreeSketchBytes,
        };
    }

    public static DeviceSnapshot ToSnapshot(DeviceRecord source, DeviceStatus status, DeviceControlPlaneState controlPlaneState)
    {
        ArgumentNullException.ThrowIfNull(source);

        return new DeviceSnapshot
        {
            DeviceId = source.DeviceId,
            Name = source.Name,
            Profile = source.Profile,
            Status = status,
            ControlPlaneState = controlPlaneState,
            IsRegistered = source.IsRegistered,
            LastSeenUtc = source.LastSeenUtc,
            FirstSeenUtc = source.FirstSeenUtc,
            LastTelemetryUtc = source.LastTelemetryUtc,
            LastAuthUtc = source.LastAuthUtc,
            ConfigState = source.ConfigState,
            LastKnownIp = source.LastKnownIp,
            LastKnownRssi = source.LastKnownRssi,
            UptimeSeconds = source.UptimeSeconds,
            LoopHealthyPercent = source.LoopHealthyPercent,
            LoopLoadPercent = source.LoopLoadPercent,
            ChipTemperatureCelsius = source.ChipTemperatureCelsius,
            FreeHeapBytes = source.FreeHeapBytes,
            LargestHeapBlockBytes = source.LargestHeapBlockBytes,
            PsramAvailable = source.PsramAvailable,
            FreePsramBytes = source.FreePsramBytes,
            LargestPsramBlockBytes = source.LargestPsramBlockBytes,
            WifiConnected = source.WifiConnected,
            WifiState = source.WifiState,
            ProvisioningPortalActive = source.ProvisioningPortalActive,
            AuxLedAvailable = source.AuxLedAvailable,
            TestLedAvailable = source.TestLedAvailable,
            LastWifiEvent = source.LastWifiEvent,
            StreamLastSequence = source.StreamLastSequence,
            StreamFramesReceived = source.StreamFramesReceived,
            StreamFramesApplied = source.StreamFramesApplied,
            Hub75PresentFrames = source.Hub75PresentFrames,
            StreamSequenceGapCount = source.StreamSequenceGapCount,
            StreamInvalidFrameCount = source.StreamInvalidFrameCount,
            ResetReason = source.ResetReason,
            ControlQueueDepth = source.ControlQueueDepth,
            ControlWorkerState = source.ControlWorkerState,
            PanelsWorkerState = source.PanelsWorkerState,
            LastSlowCommand = source.LastSlowCommand,
            LastSlowCommandDurationMs = source.LastSlowCommandDurationMs,
            FirmwareVersion = source.FirmwareVersion,
            TelemetrySequence = source.TelemetrySequence,
            BrightnessCap = source.BrightnessCap,
            BrightnessRequested = source.BrightnessRequested,
            BrightnessApplied = source.BrightnessApplied,
            TestLedEnabled = source.TestLedEnabled,
            TestLedDuty = source.TestLedDuty,
            ActiveAppId = source.ActiveAppId,
            ActiveAppName = source.ActiveAppName,
            BoardModel = source.BoardModel,
            PanelType = source.PanelType,
            AnimatedWebpBatchSupported = source.AnimatedWebpBatchSupported,
            ChipModel = source.ChipModel,
            ChipRevision = source.ChipRevision,
            ChipCores = source.ChipCores,
            CpuFreqMHz = source.CpuFreqMHz,
            SdkVersion = source.SdkVersion,
            HeapTotalBytes = source.HeapTotalBytes,
            PsramTotalBytes = source.PsramTotalBytes,
            FlashTotalBytes = source.FlashTotalBytes,
            SketchSizeBytes = source.SketchSizeBytes,
            FreeSketchBytes = source.FreeSketchBytes,
        };
    }
}
