using Device.Protocol.Models;

namespace Device.Server.Hosting;

// DOCS: docs/wiki/modules/device-server-protocol.md#fluxo-de-execucao
internal static class DeviceRecordMutations
{
    public static DeviceRecord CreatePairedRecord(
        string deviceId,
        string token,
        string name,
        string profile,
        string? firmwareVersion,
        string? ip,
        string? boardModel,
        string? panelType,
        DateTimeOffset now)
    {
        return new DeviceRecord
        {
            DeviceId = deviceId,
            Token = token,
            Name = name,
            Profile = profile,
            CreatedAtUtc = now,
            LastSeenUtc = now,
            LastKnownIp = ip,
            FirmwareVersion = firmwareVersion,
            BoardModel = boardModel,
            PanelType = panelType,
            IsRegistered = true,
        };
    }

    public static DeviceRecord MarkSeen(
        DeviceRecord source,
        DateTimeOffset now,
        string? ip,
        int? rssi,
        string? firmwareVersion,
        string? activeAppId = null,
        string? activeAppName = null,
        string? boardModel = null,
        string? panelType = null)
    {
        ArgumentNullException.ThrowIfNull(source);

        return new DeviceRecord
        {
            DeviceId = source.DeviceId,
            Name = source.Name,
            Profile = source.Profile,
            Token = source.Token,
            IsRegistered = source.IsRegistered,
            CreatedAtUtc = source.CreatedAtUtc,
            LastSeenUtc = now,
            FirstSeenUtc = source.FirstSeenUtc,
            LastTelemetryUtc = source.LastTelemetryUtc,
            LastAuthUtc = source.LastAuthUtc,
            ConfigState = source.ConfigState,
            FirmwareVersion = string.IsNullOrWhiteSpace(firmwareVersion) ? source.FirmwareVersion : firmwareVersion,
            LastKnownIp = string.IsNullOrWhiteSpace(ip) ? source.LastKnownIp : ip,
            LastKnownRssi = rssi ?? source.LastKnownRssi,
            UptimeSeconds = source.UptimeSeconds,
            LoopLoadPercent = source.LoopLoadPercent,
            FreeHeapBytes = source.FreeHeapBytes,
            LargestHeapBlockBytes = source.LargestHeapBlockBytes,
            PsramAvailable = source.PsramAvailable,
            FreePsramBytes = source.FreePsramBytes,
            LargestPsramBlockBytes = source.LargestPsramBlockBytes,
            WifiConnected = source.WifiConnected,
            WifiState = source.WifiState,
            ProvisioningPortalActive = source.ProvisioningPortalActive,
            AuxLedAvailable = source.AuxLedAvailable,
            TestLedAvailable = source.TestLedAvailable,
            LastWifiEvent = source.LastWifiEvent,
            StreamLastSequence = source.StreamLastSequence,
            StreamFramesReceived = source.StreamFramesReceived,
            StreamFramesApplied = source.StreamFramesApplied,
            StreamSequenceGapCount = source.StreamSequenceGapCount,
            StreamInvalidFrameCount = source.StreamInvalidFrameCount,
            TelemetrySequence = source.TelemetrySequence,
            BrightnessCap = source.BrightnessCap,
            BrightnessRequested = source.BrightnessRequested,
            BrightnessApplied = source.BrightnessApplied,
            TestLedEnabled = source.TestLedEnabled,
            TestLedDuty = source.TestLedDuty,
            ActiveAppId = string.IsNullOrWhiteSpace(activeAppId) ? source.ActiveAppId : activeAppId,
            ActiveAppName = string.IsNullOrWhiteSpace(activeAppName) ? source.ActiveAppName : activeAppName,
            BoardModel = string.IsNullOrWhiteSpace(boardModel) ? source.BoardModel : boardModel,
            PanelType = string.IsNullOrWhiteSpace(panelType) ? source.PanelType : panelType,
        };
    }

    public static DeviceRecord MarkAuthenticated(DeviceRecord source, DateTimeOffset now)
    {
        ArgumentNullException.ThrowIfNull(source);

        return new DeviceRecord
        {
            DeviceId = source.DeviceId,
            Name = source.Name,
            Profile = source.Profile,
            Token = source.Token,
            IsRegistered = true,
            CreatedAtUtc = source.CreatedAtUtc,
            LastSeenUtc = source.LastSeenUtc,
            FirstSeenUtc = source.FirstSeenUtc ?? now,
            LastTelemetryUtc = source.LastTelemetryUtc,
            LastAuthUtc = now,
            ConfigState = DeviceConfigState.KnownGood,
            FirmwareVersion = source.FirmwareVersion,
            LastKnownIp = source.LastKnownIp,
            LastKnownRssi = source.LastKnownRssi,
            UptimeSeconds = source.UptimeSeconds,
            LoopLoadPercent = source.LoopLoadPercent,
            FreeHeapBytes = source.FreeHeapBytes,
            LargestHeapBlockBytes = source.LargestHeapBlockBytes,
            PsramAvailable = source.PsramAvailable,
            FreePsramBytes = source.FreePsramBytes,
            LargestPsramBlockBytes = source.LargestPsramBlockBytes,
            WifiConnected = source.WifiConnected,
            WifiState = source.WifiState,
            ProvisioningPortalActive = source.ProvisioningPortalActive,
            AuxLedAvailable = source.AuxLedAvailable,
            TestLedAvailable = source.TestLedAvailable,
            LastWifiEvent = source.LastWifiEvent,
            StreamLastSequence = source.StreamLastSequence,
            StreamFramesReceived = source.StreamFramesReceived,
            StreamFramesApplied = source.StreamFramesApplied,
            StreamSequenceGapCount = source.StreamSequenceGapCount,
            StreamInvalidFrameCount = source.StreamInvalidFrameCount,
            TelemetrySequence = source.TelemetrySequence,
            BrightnessCap = source.BrightnessCap,
            BrightnessRequested = source.BrightnessRequested,
            BrightnessApplied = source.BrightnessApplied,
            TestLedEnabled = source.TestLedEnabled,
            TestLedDuty = source.TestLedDuty,
            ActiveAppId = source.ActiveAppId,
            ActiveAppName = source.ActiveAppName,
            BoardModel = source.BoardModel,
            PanelType = source.PanelType,
        };
    }

    public static DeviceRecord MarkTelemetry(
        DeviceRecord source,
        DateTimeOffset now,
        string? ip,
        int? rssi,
        string? firmwareVersion,
        string? activeAppId = null,
        string? activeAppName = null,
        string? boardModel = null,
        string? panelType = null,
        int? uptimeSeconds = null,
        int? loopLoadPercent = null,
        long? freeHeapBytes = null,
        long? largestHeapBlockBytes = null,
        bool? psramAvailable = null,
        long? freePsramBytes = null,
        long? largestPsramBlockBytes = null,
        bool? wifiConnected = null,
        string? wifiState = null,
        bool? provisioningPortalActive = null,
        bool? auxLedAvailable = null,
        bool? testLedAvailable = null,
        string? lastWifiEvent = null,
        uint? streamLastSequence = null,
        uint? streamFramesReceived = null,
        uint? streamFramesApplied = null,
        uint? streamSequenceGapCount = null,
        uint? streamInvalidFrameCount = null,
        uint? telemetrySequence = null,
        int? brightnessCap = null,
        int? brightnessRequested = null,
        int? brightnessApplied = null,
        bool? testLedEnabled = null,
        int? testLedDuty = null)
    {
        ArgumentNullException.ThrowIfNull(source);

        return new DeviceRecord
        {
            DeviceId = source.DeviceId,
            Name = source.Name,
            Profile = source.Profile,
            Token = source.Token,
            IsRegistered = true,
            CreatedAtUtc = source.CreatedAtUtc,
            LastSeenUtc = now,
            FirstSeenUtc = source.FirstSeenUtc ?? now,
            LastTelemetryUtc = now,
            LastAuthUtc = source.LastAuthUtc,
            ConfigState = source.ConfigState,
            FirmwareVersion = string.IsNullOrWhiteSpace(firmwareVersion) ? source.FirmwareVersion : firmwareVersion,
            LastKnownIp = string.IsNullOrWhiteSpace(ip) ? source.LastKnownIp : ip,
            LastKnownRssi = rssi ?? source.LastKnownRssi,
            UptimeSeconds = uptimeSeconds,
            LoopLoadPercent = loopLoadPercent,
            FreeHeapBytes = freeHeapBytes,
            LargestHeapBlockBytes = largestHeapBlockBytes,
            PsramAvailable = psramAvailable,
            FreePsramBytes = freePsramBytes,
            LargestPsramBlockBytes = largestPsramBlockBytes,
            WifiConnected = wifiConnected,
            WifiState = wifiState,
            ProvisioningPortalActive = provisioningPortalActive,
            AuxLedAvailable = auxLedAvailable,
            TestLedAvailable = testLedAvailable,
            LastWifiEvent = lastWifiEvent,
            StreamLastSequence = streamLastSequence,
            StreamFramesReceived = streamFramesReceived,
            StreamFramesApplied = streamFramesApplied,
            StreamSequenceGapCount = streamSequenceGapCount,
            StreamInvalidFrameCount = streamInvalidFrameCount,
            TelemetrySequence = telemetrySequence,
            BrightnessCap = brightnessCap,
            BrightnessRequested = brightnessRequested,
            BrightnessApplied = brightnessApplied,
            TestLedEnabled = testLedEnabled,
            TestLedDuty = testLedDuty,
            ActiveAppId = string.IsNullOrWhiteSpace(activeAppId) ? source.ActiveAppId : activeAppId,
            ActiveAppName = string.IsNullOrWhiteSpace(activeAppName) ? source.ActiveAppName : activeAppName,
            BoardModel = string.IsNullOrWhiteSpace(boardModel) ? source.BoardModel : boardModel,
            PanelType = string.IsNullOrWhiteSpace(panelType) ? source.PanelType : panelType,
        };
    }

    public static DeviceSnapshot ToSnapshot(DeviceRecord source, DeviceStatus status, DeviceControlPlaneState controlPlaneState)
    {
        ArgumentNullException.ThrowIfNull(source);

        return new DeviceSnapshot
        {
            DeviceId = source.DeviceId,
            Name = source.Name,
            Profile = source.Profile,
            Status = status,
            ControlPlaneState = controlPlaneState,
            IsRegistered = source.IsRegistered,
            LastSeenUtc = source.LastSeenUtc,
            FirstSeenUtc = source.FirstSeenUtc,
            LastTelemetryUtc = source.LastTelemetryUtc,
            LastAuthUtc = source.LastAuthUtc,
            ConfigState = source.ConfigState,
            LastKnownIp = source.LastKnownIp,
            LastKnownRssi = source.LastKnownRssi,
            UptimeSeconds = source.UptimeSeconds,
            LoopLoadPercent = source.LoopLoadPercent,
            FreeHeapBytes = source.FreeHeapBytes,
            LargestHeapBlockBytes = source.LargestHeapBlockBytes,
            PsramAvailable = source.PsramAvailable,
            FreePsramBytes = source.FreePsramBytes,
            LargestPsramBlockBytes = source.LargestPsramBlockBytes,
            WifiConnected = source.WifiConnected,
            WifiState = source.WifiState,
            ProvisioningPortalActive = source.ProvisioningPortalActive,
            AuxLedAvailable = source.AuxLedAvailable,
            TestLedAvailable = source.TestLedAvailable,
            LastWifiEvent = source.LastWifiEvent,
            StreamLastSequence = source.StreamLastSequence,
            StreamFramesReceived = source.StreamFramesReceived,
            StreamFramesApplied = source.StreamFramesApplied,
            StreamSequenceGapCount = source.StreamSequenceGapCount,
            StreamInvalidFrameCount = source.StreamInvalidFrameCount,
            FirmwareVersion = source.FirmwareVersion,
            TelemetrySequence = source.TelemetrySequence,
            BrightnessCap = source.BrightnessCap,
            BrightnessRequested = source.BrightnessRequested,
            BrightnessApplied = source.BrightnessApplied,
            TestLedEnabled = source.TestLedEnabled,
            TestLedDuty = source.TestLedDuty,
            ActiveAppId = source.ActiveAppId,
            ActiveAppName = source.ActiveAppName,
            BoardModel = source.BoardModel,
            PanelType = source.PanelType,
        };
    }
}
